services:
  nginx:
      build: requirements/nginx/.
      image: nginx:vsb1.2
      container_name: nginx
      env_file:
        - .env
      volumes:
        - v_wordpress:/var/www/wordpress
      networks:
        - custom_net
      restart: on-failure
      ports:
        - "443:443"
      depends_on:
        - wordpress_php
  wordpress_php:
      build: requirements/wordpress/.
      image: wordpress_php:vsb1.2
      container_name: wordpress_php
      env_file:
        - .env
      secrets:
        - wp_password
        - db_password
      volumes:
        - v_wordpress:/var/www/wordpress
      networks:
        - custom_net
      restart: on-failure
      depends_on:
        - mariadb 
  mariadb:
      build: requirements/mariadb/.
      image: mariadb:vsb1.2
      container_name: mariadb
      volumes:
        - v_mariadb:/var/lib/mysql
      networks:
        - custom_net
      restart: on-failure
      env_file:
        - .env
      secrets:
        - db_password
        - db_root_password
  redis:
      build: requirements/bonus/redis/.
      image: redis:vsb1.2
      container_name: redis
      networks:
        - custom_net
      restart: on-failure
  ftp:
      build: requirements/bonus/ftp/.
      image: ftp:vsb1.2
      container_name: ftp
      env_file:
        - .env
      secrets:
        - ftp_password
      ports:
        - "33:21"
        - "10100-10110:10100-10110"
      volumes:
        - v_wordpress:/var/data/ftp
      restart: on-failure
  adminer:
      build: requirements/bonus/Adminer/.
      image: adminer:vsb1.2
      container_name: adminer
      ports:
        - "2001:80"
      networks:
        - custom_net
      restart: on-failure
  glances:
      build: requirements/bonus/glances/.
      image: glances:vsb1.2
      container_name: glances
      ports:
        - "61208:61208"
      restart: on-failure
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /etc/os-release:/etc/os-release:ro
  tictactoe: 
      build: requirements/bonus/tictactoe/.
      image: tictactoe:vsb1.2
      container_name: tictactoe
      ports:
        - 32302:80
      restart: on-failure
volumes:
  v_wordpress:
    driver: local
    driver_opts:
      type: none
      device: "/home/sbrihamo/data/wordpress"
      o: bind
  v_mariadb:
    driver: local
    driver_opts:
      type: none
      device: "/home/sbrihamo/data/mariadb"
      o: bind
  
networks:
  custom_net:
    driver: bridge
  
secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_password:
    file: ../secrets/wp_password.txt
  ftp_password:
    file: ../secrets/ftp_password.txt