services:
  nginx:
    build: requirements/nginx/.
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "80:80"
    depends_on:
      - wordpress_php
  wordpress_php:
    env_file:
      - .env
    build: requirements/wordpress/.
    volumes:
      - wordpress:/wordpress
    depends_on:
      - mariadb  
  mariadb:
    env_file:
      - .env
    build: requirements/mariadb/.

volumes:
  wordpress:
