services:
  nginx:
    build: requirements/nginx/.
    env_file:
      - .env
    volumes:
      - v_wordpress:/var/www/wordpress
    networks:
      - custom_net
    restart: on-failure
    ports:
      - "443:443"
    depends_on:
      - wordpress_php
  wordpress_php:
    env_file:
      - .env
    build: requirements/wordpress/.
    volumes:
      - v_wordpress:/var/www/wordpress
    networks:
      - custom_net
    restart: on-failure
    depends_on:
      - mariadb 
  mariadb:
    volumes:
       - v_mariadb:/var/lib/mysql
    networks:
      - custom_net
    restart: on-failure
    env_file:
      - .env
    build: requirements/mariadb/.
  redis:
    build: requirements/bonus/redis/.
    networks:
      - custom_net
  ftp:
   build: requirements/bonus/ftp/.
   ports:
     - "21:21"
     - "10100:10100"
   volumes:
     - v_wordpress:/var/data/ftp
volumes:
  v_wordpress:
    driver: local
    driver_opts:
      type: none
      device: "/home/sbrihamo/data/wordpress"
      o: bind
  v_mariadb:
    driver: local
    driver_opts:
      type: none
      device: "/home/sbrihamo/data/mariadb"
      o: bind
networks:
  custom_net:
    driver: bridge
