<<EOF cat  
ALTER USER 'root'@'localhost' IDENTIFIED BY "$MYSQL_ROOT_PASS";
RENAME USER 'root'@'localhost' TO "$MYSQL_ROOT_NAME"@'localhost';
CREATE USER '$MYSQL_USER'@'wordpress' IDENTIFIED BY '$MYSQL_PASS';
CREATE DATABASE $MYSQL_WORDPRESS CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
EOF
